REPUTATION_MAPPING = {
    [1] = { "@Royal Woodlands/1st Reputation/Royal Woodlands - 1st Reputation",
        "@Coral Forest/1st Reputation/Coral Forest - 1st Reputation",
        "@The Marshlands/1st Reputation/The Marshlands - 1st Reputation",
        "@Scarlet Orchard/1st Reputation/Scarlet Orchard - 1st Reputation",
        "@Cursed Royal Woodlands/1st Reputation/Cursed Royal Woodlands - 1st Reputation",
        "@Coastal Grove/1st Reputation/Coastal Grove - 1st Reputation",
        "@Ashen Thicket/1st Reputation/Ashen Thicket - 1st Reputation",
        "@Sealed Forest/1st Reputation/Sealed Forest - 1st Reputation" },
    [2] = { "@Royal Woodlands/2nd Reputation/Royal Woodlands - 2nd Reputation",
        "@Coral Forest/2nd Reputation/Coral Forest - 2nd Reputation",
        "@The Marshlands/2nd Reputation/The Marshlands - 2nd Reputation",
        "@Scarlet Orchard/2nd Reputation/Scarlet Orchard - 2nd Reputation",
        "@Cursed Royal Woodlands/2nd Reputation/Cursed Royal Woodlands - 2nd Reputation",
        "@Coastal Grove/2nd Reputation/Coastal Grove - 2nd Reputation",
        "@Ashen Thicket/2nd Reputation/Ashen Thicket - 2nd Reputation",
        "@Sealed Forest/2nd Reputation/Sealed Forest - 2nd Reputation" },
    [3] = { "@Royal Woodlands/3rd Reputation/Royal Woodlands - 3rd Reputation",
        "@Coral Forest/3rd Reputation/Coral Forest - 3rd Reputation",
        "@The Marshlands/3rd Reputation/The Marshlands - 3rd Reputation",
        "@Scarlet Orchard/3rd Reputation/Scarlet Orchard - 3rd Reputation",
        "@Cursed Royal Woodlands/3rd Reputation/Cursed Royal Woodlands - 3rd Reputation",
        "@Coastal Grove/3rd Reputation/Coastal Grove - 3rd Reputation",
        "@Ashen Thicket/3rd Reputation/Ashen Thicket - 3rd Reputation",
        "@Sealed Forest/3rd Reputation/Sealed Forest - 3rd Reputation" },
    [4] = { "@Royal Woodlands/4th Reputation/Royal Woodlands - 4th Reputation",
        "@Coral Forest/4th Reputation/Coral Forest - 4th Reputation",
        "@The Marshlands/4th Reputation/The Marshlands - 4th Reputation",
        "@Scarlet Orchard/4th Reputation/Scarlet Orchard - 4th Reputation",
        "@Cursed Royal Woodlands/4th Reputation/Cursed Royal Woodlands - 4th Reputation",
        "@Coastal Grove/4th Reputation/Coastal Grove - 4th Reputation",
        "@Ashen Thicket/4th Reputation/Ashen Thicket - 4th Reputation",
        "@Sealed Forest/4th Reputation/Sealed Forest - 4th Reputation" },
    [5] = { "@Royal Woodlands/5th Reputation/Royal Woodlands - 5th Reputation",
        "@Coral Forest/5th Reputation/Coral Forest - 5th Reputation",
        "@The Marshlands/5th Reputation/The Marshlands - 5th Reputation",
        "@Scarlet Orchard/5th Reputation/Scarlet Orchard - 5th Reputation",
        "@Cursed Royal Woodlands/5th Reputation/Cursed Royal Woodlands - 5th Reputation",
        "@Coastal Grove/5th Reputation/Coastal Grove - 5th Reputation",
        "@Ashen Thicket/5th Reputation/Ashen Thicket - 5th Reputation",
        "@Sealed Forest/5th Reputation/Sealed Forest - 5th Reputation" },
    [6] = { "@Royal Woodlands/6th Reputation/Royal Woodlands - 6th Reputation",
        "@Coral Forest/6th Reputation/Coral Forest - 6th Reputation",
        "@The Marshlands/6th Reputation/The Marshlands - 6th Reputation",
        "@Scarlet Orchard/6th Reputation/Scarlet Orchard - 6th Reputation",
        "@Cursed Royal Woodlands/6th Reputation/Cursed Royal Woodlands - 6th Reputation",
        "@Coastal Grove/6th Reputation/Coastal Grove - 6th Reputation",
        "@Ashen Thicket/6th Reputation/Ashen Thicket - 6th Reputation",
        "@Sealed Forest/6th Reputation/Sealed Forest - 6th Reputation" },
    [7] = { "@Royal Woodlands/7th Reputation/Royal Woodlands - 7th Reputation",
        "@Coral Forest/7th Reputation/Coral Forest - 7th Reputation",
        "@The Marshlands/7th Reputation/The Marshlands - 7th Reputation",
        "@Scarlet Orchard/7th Reputation/Scarlet Orchard - 7th Reputation",
        "@Cursed Royal Woodlands/7th Reputation/Cursed Royal Woodlands - 7th Reputation",
        "@Coastal Grove/7th Reputation/Coastal Grove - 7th Reputation",
        "@Ashen Thicket/7th Reputation/Ashen Thicket - 7th Reputation",
        "@Sealed Forest/7th Reputation/Sealed Forest - 7th Reputation" },
    [8] = { "@Royal Woodlands/8th Reputation/Royal Woodlands - 8th Reputation",
        "@Coral Forest/8th Reputation/Coral Forest - 8th Reputation",
        "@The Marshlands/8th Reputation/The Marshlands - 8th Reputation",
        "@Scarlet Orchard/8th Reputation/Scarlet Orchard - 8th Reputation",
        "@Cursed Royal Woodlands/8th Reputation/Cursed Royal Woodlands - 8th Reputation",
        "@Coastal Grove/8th Reputation/Coastal Grove - 8th Reputation",
        "@Ashen Thicket/8th Reputation/Ashen Thicket - 8th Reputation",
        "@Sealed Forest/8th Reputation/Sealed Forest - 8th Reputation" },
    [9] = { "@Royal Woodlands/9th Reputation/Royal Woodlands - 9th Reputation",
        "@Coral Forest/9th Reputation/Coral Forest - 9th Reputation",
        "@The Marshlands/9th Reputation/The Marshlands - 9th Reputation",
        "@Scarlet Orchard/9th Reputation/Scarlet Orchard - 9th Reputation",
        "@Cursed Royal Woodlands/9th Reputation/Cursed Royal Woodlands - 9th Reputation",
        "@Coastal Grove/9th Reputation/Coastal Grove - 9th Reputation",
        "@Ashen Thicket/9th Reputation/Ashen Thicket - 9th Reputation",
        "@Sealed Forest/9th Reputation/Sealed Forest - 9th Reputation" },
    [10] = { "@Royal Woodlands/10th Reputation/Royal Woodlands - 10th Reputation",
        "@Coral Forest/10th Reputation/Coral Forest - 10th Reputation",
        "@The Marshlands/10th Reputation/The Marshlands - 10th Reputation",
        "@Scarlet Orchard/10th Reputation/Scarlet Orchard - 10th Reputation",
        "@Cursed Royal Woodlands/10th Reputation/Cursed Royal Woodlands - 10th Reputation",
        "@Coastal Grove/10th Reputation/Coastal Grove - 10th Reputation",
        "@Ashen Thicket/10th Reputation/Ashen Thicket - 10th Reputation",
        "@Sealed Forest/10th Reputation/Sealed Forest - 10th Reputation" },
    [11] = { "@Royal Woodlands/11th Reputation/Royal Woodlands - 11th Reputation",
        "@Coral Forest/11th Reputation/Coral Forest - 11th Reputation",
        "@The Marshlands/11th Reputation/The Marshlands - 11th Reputation",
        "@Scarlet Orchard/11th Reputation/Scarlet Orchard - 11th Reputation",
        "@Cursed Royal Woodlands/11th Reputation/Cursed Royal Woodlands - 11th Reputation",
        "@Coastal Grove/11th Reputation/Coastal Grove - 11th Reputation",
        "@Ashen Thicket/11th Reputation/Ashen Thicket - 11th Reputation",
        "@Sealed Forest/11th Reputation/Sealed Forest - 11th Reputation" },
    [12] = { "@Royal Woodlands/12th Reputation/Royal Woodlands - 12th Reputation",
        "@Coral Forest/12th Reputation/Coral Forest - 12th Reputation",
        "@The Marshlands/12th Reputation/The Marshlands - 12th Reputation",
        "@Scarlet Orchard/12th Reputation/Scarlet Orchard - 12th Reputation",
        "@Cursed Royal Woodlands/12th Reputation/Cursed Royal Woodlands - 12th Reputation",
        "@Coastal Grove/12th Reputation/Coastal Grove - 12th Reputation",
        "@Ashen Thicket/12th Reputation/Ashen Thicket - 12th Reputation",
        "@Sealed Forest/12th Reputation/Sealed Forest - 12th Reputation" },
    [13] = { "@Royal Woodlands/13th Reputation/Royal Woodlands - 13th Reputation",
        "@Coral Forest/13th Reputation/Coral Forest - 13th Reputation",
        "@The Marshlands/13th Reputation/The Marshlands - 13th Reputation",
        "@Scarlet Orchard/13th Reputation/Scarlet Orchard - 13th Reputation",
        "@Cursed Royal Woodlands/13th Reputation/Cursed Royal Woodlands - 13th Reputation",
        "@Coastal Grove/13th Reputation/Coastal Grove - 13th Reputation",
        "@Ashen Thicket/13th Reputation/Ashen Thicket - 13th Reputation",
        "@Sealed Forest/13th Reputation/Sealed Forest - 13th Reputation" },
    [14] = { "@Royal Woodlands/14th Reputation/Royal Woodlands - 14th Reputation",
        "@Coral Forest/14th Reputation/Coral Forest - 14th Reputation",
        "@The Marshlands/14th Reputation/The Marshlands - 14th Reputation",
        "@Scarlet Orchard/14th Reputation/Scarlet Orchard - 14th Reputation",
        "@Cursed Royal Woodlands/14th Reputation/Cursed Royal Woodlands - 14th Reputation",
        "@Coastal Grove/14th Reputation/Coastal Grove - 14th Reputation",
        "@Ashen Thicket/14th Reputation/Ashen Thicket - 14th Reputation",
        "@Sealed Forest/14th Reputation/Sealed Forest - 14th Reputation" },
    [15] = { "@Royal Woodlands/15th Reputation/Royal Woodlands - 15th Reputation",
        "@Coral Forest/15th Reputation/Coral Forest - 15th Reputation",
        "@The Marshlands/15th Reputation/The Marshlands - 15th Reputation",
        "@Scarlet Orchard/15th Reputation/Scarlet Orchard - 15th Reputation",
        "@Cursed Royal Woodlands/15th Reputation/Cursed Royal Woodlands - 15th Reputation",
        "@Coastal Grove/15th Reputation/Coastal Grove - 15th Reputation",
        "@Ashen Thicket/15th Reputation/Ashen Thicket - 15th Reputation",
        "@Sealed Forest/15th Reputation/Sealed Forest - 15th Reputation" },
    [16] = { "@Royal Woodlands/16th Reputation/Royal Woodlands - 16th Reputation",
        "@Coral Forest/16th Reputation/Coral Forest - 16th Reputation",
        "@The Marshlands/16th Reputation/The Marshlands - 16th Reputation",
        "@Scarlet Orchard/16th Reputation/Scarlet Orchard - 16th Reputation",
        "@Cursed Royal Woodlands/16th Reputation/Cursed Royal Woodlands - 16th Reputation",
        "@Coastal Grove/16th Reputation/Coastal Grove - 16th Reputation",
        "@Ashen Thicket/16th Reputation/Ashen Thicket - 16th Reputation",
        "@Sealed Forest/16th Reputation/Sealed Forest - 16th Reputation" },
    [17] = { "@Royal Woodlands/17th Reputation/Royal Woodlands - 17th Reputation",
        "@Coral Forest/17th Reputation/Coral Forest - 17th Reputation",
        "@The Marshlands/17th Reputation/The Marshlands - 17th Reputation",
        "@Scarlet Orchard/17th Reputation/Scarlet Orchard - 17th Reputation",
        "@Cursed Royal Woodlands/17th Reputation/Cursed Royal Woodlands - 17th Reputation",
        "@Coastal Grove/17th Reputation/Coastal Grove - 17th Reputation",
        "@Ashen Thicket/17th Reputation/Ashen Thicket - 17th Reputation",
        "@Sealed Forest/17th Reputation/Sealed Forest - 17th Reputation" },
}
